NAME = ambiancechanger

CONFIG(sdk): DEPLOYMENT_PREFIX=/opt/sdk/

BINDIR = $${DEPLOYMENT_PREFIX}/bin
SHAREDIR = $${DEPLOYMENT_PREFIX}/share/$${NAME}
APPLICATIONSDIR = $${DEPLOYMENT_PREFIX}/share/applications

